# Generated by Django 3.2.12 on 2024-03-15 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_followerscount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followerscount',
            old_name='user',
            new_name='followed',
        ),
    ]
